// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.
import easyRpc

public struct EasyRpcMethod { public let service: String; public let name: String; public let path: String; public let serverStream: Bool; public init(_ s:String,_ n:String,_ p:String,_ ss:Bool){service=s;name=n;path=p;serverStream=ss} }

public let easyRpcMethodSpecs: [EasyRpcMethod] = [
  EasyRpcMethod("ConformanceService","Health","/easyrpc.conformance.v1.ConformanceService/Health",false),
  EasyRpcMethod("ConformanceService","Echo","/easyrpc.conformance.v1.ConformanceService/Echo",false),
  EasyRpcMethod("ConformanceService","Count","/easyrpc.conformance.v1.ConformanceService/Count",true),
  EasyRpcMethod("ConformanceService","Fail","/easyrpc.conformance.v1.ConformanceService/Fail",false),
]
