#!/usr/bin/env python3
# protoc-gen-easyrpc-swift: emit <file>_easyrpc.swift strong-typed client.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            pp=rest_path(m) or f'/{pkg}.{svc.name}/{m.name}'
            out.append((svc.name, m.name or '', pp, m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out



def rest_path(m):
    opts=m.options
    if not opts: return None
    try:
        raw=opts.SerializeToString(); pos=0
        while pos < len(raw):
            tag,pos=readvar(raw,pos); field=tag>>3; wt=tag&7
            if wt==2:
                ln,pos=readvar(raw,pos); val=raw[pos:pos+ln]; pos+=ln
                if field==72295728:
                    p=parse_rule(val)
                    if p: return p
            elif wt==0: _,pos=readvar(raw,pos)
            elif wt==5: pos+=4
            elif wt==1: pos+=8
    except Exception: return None
    return None
def readvar(b,i):
    v=0;s=0
    while True:
        if i>=len(b): return v,i
        x=b[i]; i+=1; v|=(x&0x7f)<<s; s+=7
        if not (x&0x80): break
    return v,i
def parse_rule(d):
    i=0
    while i<len(d):
        tag,i=readvar(d,i); field=tag>>3; wt=tag&7
        if wt==2:
            ln,i=readvar(d,i); val=d[i:i+ln].decode(); i+=ln
            if field in (2,4,3,6): return val
        elif wt==0: _,i=readvar(d,i)
        elif wt==5: i+=4
        elif wt==1: i+=8
    return None
def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=['// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.','import easyRpc','','public final class ConformanceServiceClient {','  private let t: any Transport','  public init(_ t: any Transport) { self.t = t }','']
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append(f'  public func {camel(name)}(req: Easyrpc_Conformance_V1_{it}) async throws -> AsyncThrowingStream<Easyrpc_Conformance_V1_{ot}, Error>')
                L.append(f'  {{ AsyncThrowingStream {{ cont in Task {{ do {{ let st = try await t.openStream(Request(url: "{path}", body: try req.serializedData()))')
                L.append(f'    while let msg = await st.recv() {{ cont.yield(try Easyrpc_Conformance_V1_{ot}(serializedBytes: msg)) }}')
                L.append(f'    cont.finish() }} catch {{ cont.finish(throwing: error) }} }} }} }}')
            else:
                L.append(f'  public func {camel(name)}(req: Easyrpc_Conformance_V1_{it}) async throws -> Easyrpc_Conformance_V1_{ot} {{')
                L.append(f'    let res = try await t.send(Request(url: "{path}", body: try req.serializedData()))')
                L.append(f'    if let e = res.error {{ throw e }}')
                L.append(f'    return try Easyrpc_Conformance_V1_{ot}(serializedBytes: res.body)')
                L.append('  }')
            L.append('')
        L.append('}')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.swift', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
