#!/usr/bin/env python3
# protoc-gen-easyrpc-swift: emit <file>_easyrpc.swift strong-typed client.
import sys
from google.protobuf.compiler import plugin_pb2 as plugin

def resolve(f):
    out=[]
    pkg=f.package or ''
    for svc in f.service:
        for m in svc.method:
            out.append((svc.name, m.name or '', f'/{pkg}.{svc.name}/{m.name}', m.server_streaming, m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out

def main():
    data=sys.stdin.buffer.read()
    req=plugin.CodeGeneratorRequest.FromString(data)
    files=[]
    for f in req.proto_file:
        if f.name not in req.file_to_generate: continue
        ms=resolve(f)
        if not ms: continue
        base=f.name[:-6]
        L=['// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.','import easyRpc','','public final class ConformanceServiceClient {','  private let t: any Transport','  public init(_ t: any Transport) { self.t = t }','']
        for (svc,name,path,ss,it,ot) in ms:
            if ss:
                L.append(f'  public func {camel(name)}(req: Easyrpc_Conformance_V1_{it}) async throws -> AsyncThrowingStream<Easyrpc_Conformance_V1_{ot}, Error>')
                L.append(f'  {{ AsyncThrowingStream {{ cont in Task {{ do {{ let st = try await t.openStream(Request(url: "{path}", body: try req.serializedData()))')
                L.append(f'    while let msg = await st.recv() {{ cont.yield(try Easyrpc_Conformance_V1_{ot}(serializedBytes: msg)) }}')
                L.append(f'    cont.finish() }} catch {{ cont.finish(throwing: error) }} }} }} }}')
            else:
                L.append(f'  public func {camel(name)}(req: Easyrpc_Conformance_V1_{it}) async throws -> Easyrpc_Conformance_V1_{ot} {{')
                L.append(f'    let res = try await t.send(Request(url: "{path}", body: try req.serializedData()))')
                L.append(f'    if let e = res.error {{ throw e }}')
                L.append(f'    return try Easyrpc_Conformance_V1_{ot}(serializedBytes: res.body)')
                L.append('  }')
            L.append('')
        L.append('}')
        content='\n'.join(L)
        files.append(plugin.CodeGeneratorResponse.File(name=base+'_easyrpc.swift', content=content))
    resp=plugin.CodeGeneratorResponse(file=files)
    sys.stdout.buffer.write(resp.SerializeToString())

def camel(s): return s[:1].lower()+s[1:]
if __name__=='__main__': main()
