#!/usr/bin/env python3
# protoc-gen-easyrpc-swift: emit <file>_easyrpc.swift strong-typed client.
#
# Package-aware: the Swift message type prefix is derived from the proto package
# (agent.v1 -> Easyrpc_Agent_V1, conformance.v1 -> Easyrpc_Conformance_V1).
import os
import sys
from google.protobuf.compiler import plugin_pb2 as plugin


def resolve(f):
    out = []
    pkg = f.package or ''
    for svc in f.service:
        for m in svc.method:
            pp = f'/{pkg}.{svc.name}/{m.name}'
            out.append((svc.name, m.name or '', pp, m.server_streaming,
                        m.input_type.split('.')[-1], m.output_type.split('.')[-1]))
    return out



def readvar(b, i):
    v = 0
    s = 0
    while True:
        if i >= len(b):
            return v, i
        x = b[i]
        i += 1
        v |= (x & 0x7f) << s
        s += 7
        if not (x & 0x80):
            break
    return v, i


def parse_rule(d):
    i = 0
    while i < len(d):
        tag, i = readvar(d, i)
        field = tag >> 3
        wt = tag & 7
        if wt == 2:
            ln, i = readvar(d, i)
            val = d[i:i + ln].decode()
            i += ln
            if field in (2, 4, 3, 6):
                return val
        elif wt == 0:
            _, i = readvar(d, i)
        elif wt == 5:
            i += 4
        elif wt == 1:
            i += 8
    return None


def swift_prefix(pkg):
    # 'easyrpc.conformance.v1' -> 'Easyrpc_Conformance_V1'; ensure easyrpc leading.
    parts = [x[:1].upper() + x[1:] for x in (pkg or 'easyrpc').split('.') if x]
    return '_'.join(parts)


def main():
    data = sys.stdin.buffer.read()
    req = plugin.CodeGeneratorRequest.FromString(data)
    files = []
    for f in req.proto_file:
        if f.name not in req.file_to_generate:
            continue
        ms = resolve(f)
        if not ms:
            continue
        base = f.name[:-6]
        pre = os.environ.get('EASYRPC_SWIFT_MSG_PREFIX', swift_prefix(f.package or 'easyrpc'))
        # One output file per SERVICE (multi-service protos must not collapse
        # into a single class).
        service_names = sorted({svc for (svc, _n, _p, _s, _i, _o) in ms})
        multi = len(service_names) > 1
        for svc_name in service_names:
            methods = [x for x in ms if x[0] == svc_name]
            client = svc_name + 'Client'
            L = ['// Code generated by protoc-gen-easyrpc-swift. DO NOT EDIT.', 'import easyRpc', '',
                 f'public final class {client} {{',
                 '  private let t: any Transport',
                 f'  public init(_ t: any Transport) {{ self.t = t }}',
                 '  public var lastTrailers: Headers = [:]',
                 '  public var lastStream: (any Stream)?', '']
            for (svc, name, path, ss, it, ot) in methods:
                if ss:
                    L.append(f'  public func {camel(name)}(req: {pre}_{it}, kind: String = "proto") async throws -> AsyncThrowingStream<{pre}_{ot}, Error>')
                    L.append(f'  {{ AsyncThrowingStream {{ cont in Task {{ do {{ let ct = contentTypeFor(true, kind); let st = try await t.openStream(Request(url: "{path}", headers: ["content-type": [ct]], body: frame(try encodeMsg(req, kind))))')
                    L.append('    self.lastStream = st')
                    L.append(f'    while let msg = await st.recv() {{ cont.yield(try decodeMsg(msg, {pre}_{ot}.self, kind)) }}')
                    L.append(f'    if let e = st.lastError() {{ throw e }}')
                    L.append(f'    cont.finish() }} catch {{ cont.finish(throwing: error) }} }} }} }}')
                else:
                    L.append(f'  public func {camel(name)}(req: {pre}_{it}, kind: String = "proto") async throws -> {pre}_{ot} {{')
                    L.append('    let ct = contentTypeFor(false, kind)')
                    L.append(f'    let res = try await t.send(Request(url: "{path}", headers: ["content-type": [ct]], body: try encodeMsg(req, kind)))')
                    L.append('    self.lastTrailers = res.trailers')
                    L.append(f'    if let e = res.error {{ throw e }}')
                    L.append(f'    return try decodeMsg(res.body, {pre}_{ot}.self, kind)')
                    L.append('  }')
                L.append('')
            L.append('}')
            suffix = ('_' + svc_name) if multi else ''
            content = '\n'.join(L)
            files.append(plugin.CodeGeneratorResponse.File(name=base + suffix + '_easyrpc.swift', content=content))
    resp = plugin.CodeGeneratorResponse(file=files)
    resp.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    sys.stdout.buffer.write(resp.SerializeToString())


def camel(s):
    return s[:1].lower() + s[1:]


if __name__ == '__main__':
    main()
